# Optional funding configuration – customize or remove
# github: your-org-or-user
# patreon: your-id
# open_collective: your-collective
# ko_fi: your-id
# liberapay: your-id
# issuehunt: your-id
# thanks_dev: your-id
# custom: ['https://your.custom.link']

